<a href="https://colab.research.google.com/github/aminrohan892/handsonwithpython/blob/master/linear_algebra/Chapter_2_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 2 - Linear Algebra:

## The following notebook is based on the \*Mathematics For Machine Learning\* textbook written by:
*   Marc Peter Deisenroth
*   A. Aldo Faisal
*   Cheng Soon Ong

## What does this notebook contain?

# What is a Linear Algebra?
*   Linear Algebra is the study of Vectors and certain rules to manipulate Vectors.


# What is a Vector?
*   Vector is an object that can be added together and multiplied by scalars to produce another object of the same kind.
*   Any object satisfying this condition is considered a Vector.
*   Eg:-
    * Geometric vectors
    * Polynomials
    * Audio Signals
    * Elements of $R^n$ (tuples of *n* real numbers)

# One major concept in Mathematics is the idea of *Closure*:
* This is basically asking a question: - *What is the set of all things that can result from our proposed solution?*
* In the case of Vectors: - *What is the set of Vectors that can result by starting with a small set of vectors, and adding them to each other and scaling them?*
    *   This results in: - **Vector Space**

# 2.1 Systems of Linear Equation:

## Geometric Interpretation of Systems of Linear Equations
* Let us consider a system of linear equations with two variables $x_1$, $x_2$.
* Each linear equation defines a line on the $x_1$,$x_2$-plane.
* The **solution** to a system of linear equations must satisfy all equations simultaneously. However, the **solution set** is the intersection of these lines.
* The intersection set can be:
    * line (when the lines overlap)
    * a point (only one point of intersection)
    * or empty (when lines are parallel)
* A systematic approach for solving **systems of linear equations** that contains higher number of variables is to collect all the variables, coefficient & outputs into **Vectors** and then represent them in **Matrices**.

# 2.2 Matrices:


In [ ]:
# Simple Representation of 2x3 Matrix using Arrays:
import numpy as np

A = np.array([[1,2,3],
             [4,5,6]])
print(A)


## 2.2.1 Matrix Addition & Multiplication


### Addition of two Matrices is defined as the element wise sum:

In [ ]:
# Define two Matrix A & B and then perform addition:
import numpy as np

A = np.array([[10,20],[11,22]])
B = np.array([[30,40],[33,44]])
C = A + B
print(f"Matrix A is: {A}")
print(f"Matrix B is: {B}")
print(f"Sum of Matrix A & B is: {C}")

### Whereas in Multiplication of two Matrices:
* The neighbouring dimensions should match.
    * i.e If matrix A is m$\times$n then it can only multiply with a matrix with dimension n$\times$k
* Then we multiply the element of the *m*th row of A with *k*th column of B and sum them up

### Matrix Multiplication Properties:
* It is **Not Commutative**, i.e AB $\neq$ BA
* It is **Associative**, i.e (AB)C = A(BC)
* It is **Distributive**, i.e (A+B)C = AC + BC
* Multiplication with **Identity** matrix, i.e $I_n$A = A$I_n$ = A
    *   identity Matrix is the one in which all the elements are 0 except the diagonals which are 1.

In [3]:
# Define two Matrix A & B and then perform multiplication:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[6,7],[8,9],[10,11]])
C = A @ B # In Python if we want to Multiply two Array as Matrix Multiplication we should use @ instead of *
print(f"Matrix A is: \n {A}")
print(f"Matrix B is: \n {B}")
print(f"Mulitplication of AB is: \n {C}")

# This operation will result in Hadamard Product in which the elementwise Multiplication is happening
# But this code will give us an error as for Hadamard Product the dimensions of both the Matrices should be same.
#D = A * B
#print(f"Hadamard Product :  \n {D}")

# It is Not Commutative:
E = B @ A
print(f"Mulitplication of BA is: \n {E}")

# It is Associative:
F = np.array([[3,5,8,2,1],[9,10,4,7,8]])
print(f"(AB)F is: \n {(A @ B) @ F}")
print(f"A(BF) is: \n {A @ (B @ F)}")

Matrix A is: 
 [[1 2 3]
 [4 5 6]]
Matrix B is: 
 [[ 6  7]
 [ 8  9]
 [10 11]]
Mulitplication of AB is: 
 [[ 52  58]
 [124 139]]
Mulitplication of BA is: 
 [[34 47 60]
 [44 61 78]
 [54 75 96]]
(AB)F is: 
 [[ 678  840  648  510  516]
 [1623 2010 1548 1221 1236]]
A(BF) is: 
 [[ 678  840  648  510  516]
 [1623 2010 1548 1221 1236]]


## 2.2.2 Inverse & Transpose:


### Inverse:
* Let us consider a square matrix A.
* Then let us consider another matrix B, which has a property **AB = $I_n$ = BA**
* Then we call the matrix B as the Inverse of A and is represented as **$A^{-1}$**
* Not all matrix has an inverse.
* If a matrix has an inverse, it will be Unique. That matrix will be called *regular/invertible/nonsigular*.
* If a matrix doesn't posses an inverse, it is called *irregular/noninvertible/singular*.

#### Inverse Properties:
* A$A^{-1}$ = I = $A^{-1}$A
* $(AB)^{-1}$ = $B^{-1}$$A^{-1}$
* $(A+B)^{-1}$ = $A^{-1}$+$B^{-1}$

In [2]:
import numpy as np
from numpy.linalg import inv

A = np.array([[1,2,1],[4,4,5],[6,7,7]])
B = np.array([[-7,-7,6],[2,1,-1],[4,5,-4]])

# Check if B is an Inverse of A
print(f"AB is: \n {A@B}")
print(f"BA is: \n {B@A}")

# Now use the numpy Inverse method to identify the Inverse of A:
print(f"A inverse is : \n {inv(A)}")

AB is: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
BA is: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
A inverse is : 
 [[-7. -7.  6.]
 [ 2.  1. -1.]
 [ 4.  5. -4.]]


### Transpose:
* Let us consider a matrix A and B such that **$b_{ij}$ = $a_{ji}$**
* Then we call B as the Transpose of A.
* In general, $A^T$ can be obtained by writing the columns of A as the rows of $A^T$.

#### Transpose Properties:
* $($$A^T$$)^T$ = A
* $(AB)^T$ = $B^T$$A^T$
* $(A+B)^T$ = $A^T$+$B^T$




In [6]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A_transpose = np.transpose(A)
B_transpose = np.transpose(B)

# Check for one of the transpose properties:
AB_transpose = np.transpose(A@B)
B_transpose_A_transpose = B_transpose @ A_transpose

print(f"AB transpose is: \n {AB_transpose}")
print(f"B transpose multiplied with A transpose is: \n {B_transpose_A_transpose}")

# Both the results are matching

AB transpose is: 
 [[19 43]
 [22 50]]
B transpose multiplied with A transpose is: 
 [[19 43]
 [22 50]]


## 2.2.3 Multiplication by a Scalar:

In [8]:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
print(f"A matrix is: \n {A}")

B = 3*A

print(f"A matrix is multiplied by a Scalar value and the result matrix is: \n {B}") # Each element of Matrix A is multiplied with the scalar variable


A matrix is: 
 [[1 2 3]
 [4 5 6]]
A matrix is multiplied by a Scalar value and the result matrix is: 
 [[ 3  6  9]
 [12 15 18]]


## 2.2.4 Compact Representation of Systems of Linear Equation:

* Let us consider the following system of Linear Equations:
  * 2$x_1$ + 3$x_2$ + 5$x_3$ = 1
  * 4$x_1$ - 2$x_2$ - 7$x_3$ = 8
  * 9$x_1$ + 5$x_2$ - 3$x_3$ = 2
* This system can be written in a compacted Matrix form as:
$$\begin{bmatrix} 2 & 3 & 5 \\ 4 & -2 & -7 \\ 9 & 5 & -3 \end{bmatrix}$$ * $$\begin{bmatrix} x1 \\ x2 \\ x3 \end{bmatrix}$$ = $$\begin{bmatrix} 1 \\ 8 \\ 2 \end{bmatrix}$$

* In other words we can write **A*x*=b**. 
  * Where **A*x*** is the linear combination of the columns of A matrix

# 2.3 Solving Systems of Linear Equations:

* In this section we will look into how to solve systems of Linear Equations using various ways and also provide an Algorithm for finding the Inverse of a Matrix.